# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Infra and Azure Web App - webhook-for-gh-blizz

on:
  push:
    branches:
      [NONE]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/repos

        # upload web app artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/repos

      - name: debugging
        run: | 
          pwd
          ls -la
      
        # upload ARM template artifacts 
      - name: Upload ARM template for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: infrastructure
          path: ./infra
          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

        # Download ARM templates
      - name: Download ARM templates from build job
        uses: actions/download-artifact@v2
        with:
          name: infrastructure 

        # Log into Azure 
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy infrastructure 
      - name: Deploy infrastructure
        id: deploy-infrastructure
        uses: azure/arm-deploy@v1
        with: 
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: "webhook-for-gh-rg"
          template: ./template.json
          parameters: parameters.json

        # Download .net app
      - name: Download .net-app artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

        # Deploy web app to Azure 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webhook-for-gh-blizz'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8C30EE2B9B154683ACCC33BFAB7D7A34 }}
          package: .
#          slot-name: 'Production'
